version: '3'

services:
  mysql:
    image: mysql
    ports:
      - $MYSQL_TCP_PORT:3306
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
