version: '3'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment: &mysql
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
